core:
  command-aliases: goldenchallenges,challenges
  lang: en
  prefix: GoldenChallenges

data:
  auto-save: 15
  storage:
    type: sqlite
    username: none
    password: none
    host: none
    database: none
  purge:
    enabled: false
    days: 60

challenge-types:
  DAILY: true
  WEEKLY: true
  MONTHLY: true

gui:
  title: Challenges
  size: 27
  content:
    daily:
      material: PLAYER_HEAD
      name: '&e&lDaily Challenges'
      lore:
      - '&bAvailable: &a%available-daily%'
      skull-hash: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjA4NmE5NTBkMGEzMDNmNDhhYWIzYTVmMmY2YTQwMzNlODBiYWZjYWY3Y2I1YmRhMTM5N2I4M2U1MjlmNjNiNSJ9fX0=
      slots: 10
      type: DAILY
    weekly:
      material: PLAYER_HEAD
      name: '&c&lWeekly Challenges'
      lore:
      - '&bAvailable: &a%available-weekly%'
      skull-hash: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMThkYjBhMWUxNTA1YTc3OTA1YjczNDgwNjdkZDJlYjRmODdmMWFhZjllNDg5ZjY3MGQ4MmQzYjdkNGM0YWU1MCJ9fX0=
      slots: 13
      type: WEEKLY
    monthly:
      material: PLAYER_HEAD
      name: '&d&lMonthly Challenges'
      lore:
      - '&bAvailable: &a%available-monthly%'
      skull-hash: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzY3N2U2NWRmMjk5OWQwMzE5ZmRiY2JhM2MwOTJmMTYwYjk5YjRiNDY3OTgzYWY4MWZjZmExZWI0NWQzOWEzIn19fQ==
      slots: 16
      type: MONTHLY